name: Executar main.py

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Executar main.py
        run: python main.py

      - name: Subir resultado.json no repositório
        run: |
          git config user.name "Isabela-SAG"
          git config user.email "isabela_sag@github.com"
          git add scraped_profiles .json
          git commit -m "Atualizando scraped_profiles .json automaticamente"
          git push
